{
 "title": "NATS Overview",
 "tags": [
  "ekyc",
  "nats"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "NATS Messages Published",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nats_messages_published_total[5m])) by (job)"
    }
   ]
  },
  {
   "title": "NATS Messages Delivered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nats_messages_delivered_total[5m])) by (job)"
    }
   ]
  },
  {
   "title": "NATS Server Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nats_server_info" }
   ]
  },
  {
   "title": "NATS Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nats_server_connections" }
   ]
  }
 ]
}